language: python
python:
- 3.7
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
- pip install -r requirements_dev.txt
- pip install -U tox-travis
script:
- tox
- coverage run --source parse_quest_manual -m py.test
- coverage report -m --fail-under=90
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sjcasey
  password:
    secure: vc8ThDljZSWgQq3vZRbutqo5alCQxs251K88C7p4wl9dudNEP6ONgiWk0J2gLkEa4F4gEUD76WvsqqSQNdXcCHt7yD7O6CVdi4IprLA2u8OkYbZr5TDfL+qQ6+DQLUTdyB/DLxju7/mZeE7BH8Lnh3mBiWjrxbqfxS/FWSNgmGRjzFD1z1KXcRGcTd/e+fai2tgpag9X9KTDIjW+Ee/qC/aLgT827sHsxQmt+PPKBPWpk7hj1kMn90imT1X+vr7IgQrVOGLomhyGJDN1OnAcTDaV2OnkZWxOZgdufhY2+6+B5BghSyaCiv8ZjUTae06o70t4qVeCJ3yUtlvmiq9gp5N2IXOXM5lo5hAIJ4zNd5FqzRuSRK0wyFKBbiKmSu+OL/wC4SAWJjMPGA0WF77JQHWxckS8pOK0aL1FQtQ35bM3aD0VmptJ+abw+M41Pe0gLzdKp/h/SEqZWxxyOucuofNLpWwqpb0fjT5dpqIQbrVsLujJSARA89Tg448YdANdon1bWEXBJf0IHpavoqNOZ/ydcdppX7RLXHPEM+YmGDHDwI8r1GxpDQkSxBDIDJLhFoLTIFAsEwMgvcKwWX1oVmLBYPgtnPbbHpst3wzHkSDAqAj1ZZcTgmt3+T261Ew1cFJ4xCzfa+Q6ULyDBPVO3o5uVhxm7+4cjLm3bheX+fM=
  on:
    branch: master
    repo: sjcasey21/parse_quest_manual
    python: 3.7
