language: python
python:
- 3.7
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
- pip install -r requirements_dev.txt
- pip install -U tox-travis
script:
- tox
- coverage run --source parse_quest_manual -m py.test
- coverage report -m --fail-under=90
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sjcasey
  on:
    branch: master
    repo: sjcasey21/parse_quest_manual
    python: 3.7
  password:
    secure: thyIyvdUJwpNekwXenmfSq8DRo92SO2djFokRNr4KwgFcaLHMecUy5+TelS896YkpL7+i3G9B1fqoljJA7qAS9VtRxYj5B07wXSo1d4BPaaP6WGhTCz7tIK94M+EAmjKv3JVl5TkU/TKDwKNyin4f/aYSNTEjdS9wOw9UUKu//8pUy5BlNJXv44zPklYbCiFUeodgBYRXFarNxUHHIFA57evBSqIcZZJXs+7kaczWwQHiboDXmBdwVQd7yC88vyWDJs++aS+/hCeZW0rPXOuHWF0W7Bu79sCoLdx4NF4CJg8fK7cWlLJ49Kf5U3pAIOupzdXeUA5kmROH7MZxcaI/MxIZCb+nGB8YxwHEPu3tqC5JTt3akhWw4JFZdolA9ssH2tmGPhw15uzU4gsRCVYMzif+BjouEa+SjN20FjueqP4u0IQhRIoNVoQPOyKIFedYPGPJ+C2RN7jcu9OzRreZXl0UbhaqJyCNOlHB2wIQ91RB5StxN4Oe9v3foGYjgxxGWCLgje5RGwsUKXWf+vmoUUR2K4TDq2zOv5nsw33KfbnxYuyf6+avXWF+0t2kqmg2UJwA7Y1o+ndaGuVPlWLG6wxtMwcLY3dHCctLIcOQR7P4ohBPkqmsq46R6SDkjYnRVEfPDhJkxFloBxNLUafc3OqUb7hqJ8lZ91BVG/0Cqw=
